name: test+build type-injector-lib

on:
  push:
    branches: [ "main" ]
    tags: ["v*"]
  pull_request:
    branches: [ "main" ]

env:
  NODE_VERSION: 16

jobs:
  build:
    name: build + test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup node Node.js ${{env.NODE_VERSION}}
      uses: actions/setup-node@v3
      with:
        node-version: ${{env.NODE_VERSION}}
        cache: npm
        cache-dependency-path: '*/package-lock.json'
    - run: bash build.sh
